### PR TITLE
Debug 0.13 Tests

### PR DESCRIPTION
**Pull request by mwachs5**
What else is required to get the test changes merged in...? Do we need to add them back to the test regression?

### CODE REVIEW

**Comment by mwachs5** [comment]
Which ones? I think the "*Invalid" ones don't really work, are there others?

**Comment by palmer-dabbelt** [comment]
@mwachs5 The tests should all pass on Spike now, I think we should merge this.

**Comment by mwachs5** [comment]
sounds good to me

**Comment by mwachs5** [comment]
Does 'debug-check' actually run?

**Comment by palmer-dabbelt** [comment]
With my latest commit, "debug-check" runs.  We need to merge spike before we can merge this.

**Pull request merged**
